# Generated by Django 4.1.7 on 2023-07-18 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_skill_profile_delete_jobapplication'),
        ('applications', '0003_alter_jobapplication_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='jobs.category'),
        ),
    ]
