# Generated by Django 4.1.7 on 2023-06-01 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_detail', models.TextField()),
                ('job_level', models.CharField(max_length=255)),
                ('dateline', models.DateTimeField()),
                ('posted_on', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_category', to='jobs.category')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(max_length=255)),
                ('job_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_qualifications', to='jobs.jobdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility_name', models.CharField(max_length=255)),
                ('job_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_responsibilities', to='jobs.jobdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('job_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.jobdetail')),
            ],
        ),
        migrations.RemoveField(
            model_name='qualifications',
            name='job',
        ),
        migrations.RemoveField(
            model_name='responsibilities',
            name='job',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='job',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='JobDetails',
        ),
        migrations.DeleteModel(
            name='Qualifications',
        ),
        migrations.DeleteModel(
            name='Responsibilities',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
