version: '3.9'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile
    image: moringa-portal:v1

    ports:
      - 8000:8000
    volumes:
      - ./app:/app

    command: sh -c "chmod +x /app/entrypoint.sh && chmod +x /app/migrate.sh && sh /app/migrate.sh && sh /app/entrypoint.sh"

    depends_on:
      - db
      - elasticsearch


  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    
    environment:
      - POSTGRES_USER=jerumanu
      - POSTGRES_PASSWORD=jeru@123
      - POSTGRES_DB=portal
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # Adjust JVM memory settings as needed
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  postgres_data:

