# Generated by Django 4.1.7 on 2023-06-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft', '0002_cat_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
