# Generated by Django 4.1.7 on 2023-07-18 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_skills', to='profiles.profile'),
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
