# Generated by Django 4.1.7 on 2023-07-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_skill_profile_delete_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='job_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.jobdetail'),
        ),
    ]
